# Generated by Django 5.0.1 on 2024-05-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='gross_pay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.FloatField(default=0.0),
        ),
    ]
